### ISSUE TITLE
Issue with translation

### ISSUE THREAD

**Issue by KnowledgeWanderer** [fourstacks/nova-checkboxes#20]
related to #19 didn't solve
did this and I get array to string conversion

Checkboxes::make(trans('pbadmin.amenities'), Amenity::class)
                ->options(\App\Amenity::all()->pluck('name')->all())
                ->columns(2)
my problem is not that I don't get the values, that works, the problem is that the make() method of your class doesn't seem to accept localization or I may be doing it wrong

If I do this

Checkboxes::make(trans('pbadmin.amenities'), 'Amenities')
                ->options(\App\Amenity::all()->pluck('name')->all())
                ->columns(2),
then there are simply no values being saved, so the pluck thing works and it returns an array because I'm doing a cast as array in the RealEstate Model

**Comment by KnowledgeWanderer** [comment]
@fourstacks help please, have a big project to deploy and I depend on this

**Comment by fourstacks** [comment]
I'd imagine that your issue is that you are using the string 'Amenities' as the key for your field:

`Checkboxes::make(trans('pbadmin.amenities'), 'Amenities')`

That second parameter is meant to match the underlying column name that you are saving to and in most apps that would usually be lower case e.g.:

`Checkboxes::make(trans('pbadmin.amenities'), 'amenities')`

You definitely shouldn't be using a fully qualified class name as your key as you demonstrated in your first example.  

I'd recommend having another read through of the main Nova docs to get a handle on fields - suspect your problem is configuration rather than this package per se
